# Generated by Django 4.0.3 on 2022-09-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mebel',
            name='url',
        ),
        migrations.AddField(
            model_name='mebel',
            name='garanty',
            field=models.TextField(default=1, max_length=100, verbose_name='Гарантия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mebel',
            name='height',
            field=models.FloatField(default=1, max_length=50, verbose_name='Высота'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mebel',
            name='length',
            field=models.FloatField(default=1, max_length=50, verbose_name='Длина'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mebel',
            name='materials',
            field=models.CharField(default=1, max_length=100, verbose_name='материалы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mebel',
            name='obiem',
            field=models.CharField(default=1, max_length=100, verbose_name='Объём'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mebel',
            name='rask_type',
            field=models.CharField(default=1, max_length=100, verbose_name='Тип раскладки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mebel',
            name='vstavka',
            field=models.CharField(default=1, max_length=100, verbose_name='вставка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mebel',
            name='weight',
            field=models.FloatField(default=1, max_length=100, verbose_name='Вес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mebel',
            name='width',
            field=models.FloatField(default=1, max_length=50, verbose_name='Ширина'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mebel',
            name='image',
            field=models.ImageField(upload_to='mebel/images/'),
        ),
        migrations.AlterField(
            model_name='mebel',
            name='price',
            field=models.FloatField(max_length=50, verbose_name='цена'),
        ),
    ]
