# Generated by Django 4.0.3 on 2022-09-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0002_remove_mebel_url_mebel_garanty_mebel_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mebel',
            name='osnovnie',
            field=models.TextField(default=1, max_length=1000, verbose_name='ОСНОВНЫЕ ПРЕИМУЩЕСТВА'),
            preserve_default=False,
        ),
    ]
