# Generated by Django 4.0.3 on 2022-09-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0003_mebel_osnovnie'),
    ]

    operations = [
        migrations.CreateModel(
            name='barnie_stulya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название ')),
                ('price', models.FloatField(max_length=50, verbose_name='цена')),
                ('image', models.ImageField(upload_to='mebel/images/')),
            ],
        ),
        migrations.CreateModel(
            name='cresla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название ')),
                ('price', models.FloatField(max_length=50, verbose_name='цена')),
                ('image', models.ImageField(upload_to='mebel/images/')),
            ],
        ),
        migrations.CreateModel(
            name='crovati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название ')),
                ('price', models.FloatField(max_length=50, verbose_name='цена')),
                ('image', models.ImageField(upload_to='mebel/images/')),
            ],
        ),
        migrations.CreateModel(
            name='divani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название ')),
                ('price', models.FloatField(max_length=50, verbose_name='цена')),
                ('image', models.ImageField(upload_to='mebel/images/')),
            ],
        ),
        migrations.CreateModel(
            name='stoli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название ')),
                ('price', models.FloatField(max_length=50, verbose_name='цена')),
                ('image', models.ImageField(upload_to='mebel/images/')),
            ],
        ),
        migrations.CreateModel(
            name='stulya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название ')),
                ('price', models.FloatField(max_length=50, verbose_name='цена')),
                ('image', models.ImageField(upload_to='mebel/images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Mebel',
        ),
    ]
