# Generated by Django 4.0.3 on 2022-09-10 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0004_barnie_stulya_cresla_crovati_divani_stoli_stulya_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='stulya',
            new_name='Mebel',
        ),
        migrations.DeleteModel(
            name='barnie_stulya',
        ),
        migrations.DeleteModel(
            name='cresla',
        ),
        migrations.DeleteModel(
            name='crovati',
        ),
        migrations.DeleteModel(
            name='divani',
        ),
        migrations.DeleteModel(
            name='stoli',
        ),
    ]
