# Generated by Django 4.0.3 on 2022-09-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0005_rename_stulya_mebel_delete_barnie_stulya_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mebel',
            name='type_mebel',
            field=models.CharField(choices=[('stulya', 'stulya'), ('stoli', 'столы'), ('barnie_stulya', 'barnie_stulya'), ('cresla', 'cresla'), ('crovati', 'crovati'), ('divani', 'divani')], default='стулья', max_length=30),
        ),
    ]
