# Generated by Django 4.0.3 on 2022-09-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0006_mebel_type_mebel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mebel',
            name='price',
            field=models.IntegerField(max_length=50, verbose_name='цена'),
        ),
    ]
