# Generated by Django 4.0.3 on 2022-09-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0007_alter_mebel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mebel',
            name='price',
            field=models.IntegerField(verbose_name='цена'),
        ),
    ]
