# Generated by Django 4.0.3 on 2022-09-18 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0008_alter_mebel_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mebel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='mebel',
            name='price',
        ),
    ]
