# Generated by Django 4.0.3 on 2022-09-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0009_remove_mebel_image_remove_mebel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mebel',
            name='type_mebel',
            field=models.CharField(choices=[('stulya', 'stulya'), ('stoli', 'stoli'), ('barnie_stulya', 'barnie_stulya'), ('cresla', 'cresla'), ('crovati', 'crovati'), ('divani', 'divani')], default='стулья', max_length=30),
        ),
    ]
