# Generated by Django 4.0.3 on 2022-09-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0014_alter_mebel_type_mebel_postimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stulia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название ')),
                ('type_mebel', models.CharField(choices=[('stulya', 'stulya'), ('stoli', 'столы'), ('barnie_stulya', 'barnie_stulya'), ('cresla', 'cresla'), ('crovati', 'crovati'), ('divani', 'divani')], default='стулья', max_length=30)),
                ('price', models.IntegerField(verbose_name='цена')),
                ('image', models.ImageField(upload_to='mebel/images/')),
            ],
        ),
    ]
