# Generated by Django 4.0.3 on 2022-09-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0017_postimage_barnie_stulya_postimage_cresla_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barnie_stulya',
            name='deep_stul',
            field=models.IntegerField(default=1, verbose_name='Глубина общая'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barnie_stulya',
            name='depp_sid',
            field=models.IntegerField(default=1, verbose_name='Глубина сиденья'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barnie_stulya',
            name='description',
            field=models.CharField(default=1, max_length=10000, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barnie_stulya',
            name='height_obj',
            field=models.IntegerField(default=1, verbose_name='Высота общая'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barnie_stulya',
            name='height_stul',
            field=models.IntegerField(default=1, verbose_name='Высота сиденья'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barnie_stulya',
            name='image1',
            field=models.ImageField(default=1, upload_to='mebel/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barnie_stulya',
            name='image2',
            field=models.ImageField(default=1, upload_to='mebel/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barnie_stulya',
            name='image3',
            field=models.ImageField(default=1, upload_to='mebel/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barnie_stulya',
            name='image4',
            field=models.ImageField(default=1, upload_to='mebel/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barnie_stulya',
            name='image5',
            field=models.ImageField(default=1, upload_to='mebel/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barnie_stulya',
            name='nojki',
            field=models.CharField(default=1, max_length=150, verbose_name='Ножки '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barnie_stulya',
            name='obivka',
            field=models.CharField(default=1, max_length=150, verbose_name='Обивка '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barnie_stulya',
            name='width_stul',
            field=models.IntegerField(default=1, verbose_name='Ширина сиденья'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cresla',
            name='image1',
            field=models.ImageField(default=1, upload_to='mebel/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cresla',
            name='image2',
            field=models.ImageField(default=1, upload_to='mebel/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cresla',
            name='image3',
            field=models.ImageField(default=1, upload_to='mebel/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cresla',
            name='image4',
            field=models.ImageField(default=1, upload_to='mebel/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cresla',
            name='image5',
            field=models.ImageField(default=1, upload_to='mebel/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='divani',
            name='image1',
            field=models.ImageField(default=1, upload_to='mebel/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='divani',
            name='image2',
            field=models.ImageField(default=1, upload_to='mebel/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='divani',
            name='image3',
            field=models.ImageField(default=1, upload_to='mebel/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='divani',
            name='image4',
            field=models.ImageField(default=1, upload_to='mebel/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='divani',
            name='image5',
            field=models.ImageField(default=1, upload_to='mebel/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mebel',
            name='image1',
            field=models.ImageField(default=1, upload_to='mebel/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mebel',
            name='image2',
            field=models.ImageField(default=1, upload_to='mebel/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mebel',
            name='image3',
            field=models.ImageField(default=1, upload_to='mebel/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mebel',
            name='image4',
            field=models.ImageField(default=1, upload_to='mebel/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mebel',
            name='image5',
            field=models.ImageField(default=1, upload_to='mebel/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stoli',
            name='image1',
            field=models.ImageField(default=1, upload_to='mebel/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stoli',
            name='image2',
            field=models.ImageField(default=1, upload_to='mebel/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stoli',
            name='image3',
            field=models.ImageField(default=1, upload_to='mebel/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stoli',
            name='image4',
            field=models.ImageField(default=1, upload_to='mebel/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stoli',
            name='image5',
            field=models.ImageField(default=1, upload_to='mebel/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stulia',
            name='image1',
            field=models.ImageField(default=1, upload_to='mebel/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stulia',
            name='image2',
            field=models.ImageField(default=1, upload_to='mebel/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stulia',
            name='image3',
            field=models.ImageField(default=1, upload_to='mebel/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stulia',
            name='image4',
            field=models.ImageField(default=1, upload_to='mebel/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stulia',
            name='image5',
            field=models.ImageField(default=1, upload_to='mebel/images/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
