# Generated by Django 4.0.3 on 2022-09-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0018_barnie_stulya_deep_stul_barnie_stulya_depp_sid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barnie_stulya',
            name='description',
            field=models.TextField(max_length=10000, verbose_name='Описание'),
        ),
    ]
