# Generated by Django 4.0.3 on 2022-09-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0019_alter_barnie_stulya_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='barnie_stulya',
            name='SRegulVisot',
            field=models.BooleanField(default=1, verbose_name='С регулировкой высоты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barnie_stulya',
            name='barStul',
            field=models.BooleanField(default=1, verbose_name='Барные стулья'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barnie_stulya',
            name='polubarStul',
            field=models.BooleanField(default=1, verbose_name='Полубарные стулья'),
            preserve_default=False,
        ),
    ]
