# Generated by Django 4.0.3 on 2022-09-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0020_barnie_stulya_sregulvisot_barnie_stulya_barstul_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stoli',
            name='diametr',
            field=models.IntegerField(default=1, verbose_name='Диаметр'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stoli',
            name='dlina',
            field=models.IntegerField(default=1, verbose_name='Длина'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stoli',
            name='height',
            field=models.IntegerField(default=1, verbose_name='Высота'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stoli',
            name='width',
            field=models.IntegerField(default=1, verbose_name='Ширина'),
            preserve_default=False,
        ),
    ]
