# Generated by Django 4.0.3 on 2022-09-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0021_stoli_diametr_stoli_dlina_stoli_height_stoli_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='stoli',
            name='nojki',
            field=models.CharField(default=1, max_length=150, verbose_name='Ножки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stoli',
            name='stoleshnitsa',
            field=models.CharField(default=1, max_length=150, verbose_name='Столешница'),
            preserve_default=False,
        ),
    ]
