# Generated by Django 4.0.3 on 2022-09-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0023_crovati_sregulvisot_crovati_barstul_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crovati',
            old_name='width_izn',
            new_name='height_izn',
        ),
        migrations.AddField(
            model_name='cresla',
            name='deep',
            field=models.IntegerField(default=1, verbose_name='Глубина'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cresla',
            name='description',
            field=models.TextField(default=1, max_length=10000, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cresla',
            name='height_obj',
            field=models.IntegerField(default=1, verbose_name='Высота общая'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cresla',
            name='height_ott',
            field=models.IntegerField(default=1, verbose_name='Высота оттоманки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cresla',
            name='height_sid',
            field=models.IntegerField(default=1, verbose_name='Высота сиденья'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cresla',
            name='image6',
            field=models.ImageField(default=1, upload_to='mebel/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cresla',
            name='image7',
            field=models.ImageField(default=1, upload_to='mebel/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cresla',
            name='napolnitel',
            field=models.CharField(default=1, max_length=150, verbose_name='Наполнитель'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cresla',
            name='nojki',
            field=models.CharField(default=1, max_length=150, verbose_name='Ножки '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cresla',
            name='obivka',
            field=models.CharField(default=1, max_length=150, verbose_name='Обивка '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cresla',
            name='ott_dlin',
            field=models.IntegerField(default=1, verbose_name='Длина'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cresla',
            name='ott_width',
            field=models.IntegerField(default=11, verbose_name='Ширина'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cresla',
            name='price1',
            field=models.IntegerField(default=1, verbose_name='цена оттоманки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cresla',
            name='width',
            field=models.IntegerField(default=1, verbose_name='Ширина'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='divani',
            name='SleepMest',
            field=models.CharField(default=1, max_length=200, verbose_name='Спальное место'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='divani',
            name='TolshSpalMest',
            field=models.IntegerField(default=1, verbose_name='Толщина спального места'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='divani',
            name='chehli',
            field=models.CharField(default=1, max_length=200, verbose_name='Чехлы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='divani',
            name='deep',
            field=models.IntegerField(default=1, verbose_name='Глубина'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='divani',
            name='deepSidBezPod',
            field=models.IntegerField(default=1, verbose_name='Глубина сиденья без подушек'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='divani',
            name='description',
            field=models.TextField(default=1, max_length=200, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='divani',
            name='height',
            field=models.IntegerField(default=1, verbose_name='Высота'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='divani',
            name='heightPod',
            field=models.IntegerField(default=1, verbose_name='Высота подлокотника'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='divani',
            name='heightSid',
            field=models.IntegerField(default=1, verbose_name='Высота сиденья'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='divani',
            name='heightSpalMest',
            field=models.IntegerField(default=1, verbose_name='Высота спального места'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='divani',
            name='mechanizm',
            field=models.CharField(default=1, max_length=200, verbose_name='Механизм'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='divani',
            name='napolnitel',
            field=models.CharField(default=1, max_length=160, verbose_name='Наполнитель'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='divani',
            name='nojki',
            field=models.CharField(default=1, max_length=200, verbose_name='Ножки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='divani',
            name='obivka',
            field=models.CharField(default=1, max_length=200, verbose_name='Обивка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='divani',
            name='width',
            field=models.IntegerField(default=1, verbose_name='Ширина'),
            preserve_default=False,
        ),
    ]
