# Generated by Django 4.0.3 on 2022-09-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0024_rename_width_izn_crovati_height_izn_cresla_deep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cresla',
            name='ObivPech',
            field=models.BooleanField(default=1, verbose_name="Обивка 'Пэчворк'"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cresla',
            name='PovCresl',
            field=models.BooleanField(default=1, verbose_name='Поворотные кресла'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cresla',
            name='StilContour',
            field=models.BooleanField(default=1, verbose_name='Стиль Contour'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cresla',
            name='StilHusk',
            field=models.BooleanField(default=1, verbose_name='Стиль Husk'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cresla',
            name='VTkanini',
            field=models.BooleanField(default=1, verbose_name='В ткани'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cresla',
            name='kresla_krovati',
            field=models.BooleanField(default=1, verbose_name='Кресла-кровати'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cresla',
            name='neraskladnoy',
            field=models.BooleanField(default=1, verbose_name='Не раскладные'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cresla',
            name='raskladnoy',
            field=models.BooleanField(default=1, verbose_name='Раскладные'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cresla',
            name='reclainer',
            field=models.BooleanField(default=1, verbose_name='Реклайнеры'),
            preserve_default=False,
        ),
    ]
