# Generated by Django 4.0.3 on 2022-09-19 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0025_cresla_obivpech_cresla_povcresl_cresla_stilcontour_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cresla',
            old_name='neraskladnoy',
            new_name='neraskladniye',
        ),
        migrations.RenameField(
            model_name='cresla',
            old_name='raskladnoy',
            new_name='raskladniye',
        ),
    ]
