# Generated by Django 4.0.3 on 2022-09-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0026_rename_neraskladnoy_cresla_neraskladniye_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crovati',
            name='Glyanez',
            field=models.BooleanField(default=1, verbose_name='Глянец'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='divani',
            name='RasplaKaKnijka',
            field=models.BooleanField(default=1, verbose_name='Раскладывается как книжка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='divani',
            name='SDvuspalKrovat',
            field=models.BooleanField(default=1, verbose_name='С двуспальной кроватью'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='divani',
            name='nerakladniye',
            field=models.BooleanField(default=1, verbose_name='Не раскладные'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='divani',
            name='rakladniye',
            field=models.BooleanField(default=1, verbose_name='Раскладные'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='divani',
            name='raskpladVpered',
            field=models.BooleanField(default=1, verbose_name='Раскладывается вперёд'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='divani',
            name='threex',
            field=models.BooleanField(default=1, verbose_name='3x местные'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='divani',
            name='two',
            field=models.BooleanField(default=1, verbose_name='2x местные'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='divani',
            name='ugol',
            field=models.BooleanField(default=1, verbose_name='Угловые'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stulia',
            name='deep',
            field=models.IntegerField(default=1, verbose_name='Глубина'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stulia',
            name='description',
            field=models.TextField(default=1, max_length=20000, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stulia',
            name='height_obj',
            field=models.IntegerField(default=1, verbose_name='Высотая общая'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stulia',
            name='height_sid',
            field=models.IntegerField(default=1, verbose_name='Высота сиденья'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stulia',
            name='nojki',
            field=models.CharField(default=1, max_length=200, verbose_name='Ножки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stulia',
            name='obivka',
            field=models.CharField(default=1, max_length=200, verbose_name='Обивка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stulia',
            name='width',
            field=models.IntegerField(default=1, verbose_name='Ширина'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crovati',
            name='SRegulVisot',
            field=models.BooleanField(verbose_name='В ткани'),
        ),
    ]
