# Generated by Django 4.0.3 on 2022-09-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0027_crovati_glyanez_divani_rasplakaknijka_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stulia',
            name='DerevOsn',
            field=models.BooleanField(default=1, verbose_name='Деревянное основание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stulia',
            name='EcoKoja',
            field=models.BooleanField(default=1, verbose_name='Эко кожа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stulia',
            name='ObivPecg',
            field=models.BooleanField(default=1, verbose_name="Обивка 'Пэчворк'"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stulia',
            name='Plastic',
            field=models.BooleanField(default=1, verbose_name='Пластик'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stulia',
            name='PovCresl',
            field=models.BooleanField(default=1, verbose_name='Поворотные кресла'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stulia',
            name='Tkanini',
            field=models.BooleanField(default=1, verbose_name='Ткань'),
            preserve_default=False,
        ),
    ]
