# Generated by Django 4.0.3 on 2022-09-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0029_alter_barnie_stulya_deep_stul_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crovati',
            old_name='polubarStul',
            new_name='bezpodmeh',
        ),
        migrations.RenameField(
            model_name='crovati',
            old_name='barStul',
            new_name='podmeh',
        ),
        migrations.RenameField(
            model_name='crovati',
            old_name='SRegulVisot',
            new_name='vtkanini',
        ),
        migrations.AlterField(
            model_name='stulia',
            name='height_obj',
            field=models.CharField(max_length=150, verbose_name='Высотая общая'),
        ),
        migrations.AlterField(
            model_name='stulia',
            name='height_sid',
            field=models.CharField(max_length=150, verbose_name='Высота сиденья'),
        ),
    ]
