# Generated by Django 4.0.3 on 2022-09-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0030_rename_polubarstul_crovati_bezpodmeh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stoli',
            name='JoutStoul',
            field=models.BooleanField(default=1, verbose_name='Журнальные столы'),
            preserve_default=False,
        ),
    ]
