# Generated by Django 4.1.2 on 2022-10-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0032_stoli_neraskladnoy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='название ')),
                ('price', models.IntegerField(verbose_name='цена')),
                ('ssilka', models.CharField(max_length=250, verbose_name='название')),
                ('image', models.ImageField(upload_to='mebel/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Novinki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='название ')),
                ('price', models.IntegerField(verbose_name='цена')),
                ('ssilka', models.CharField(max_length=250, verbose_name='название')),
            ],
        ),
    ]
