# Generated by Django 4.1.2 on 2022-10-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0033_fotki_novinki'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotki',
            name='price',
        ),
        migrations.RemoveField(
            model_name='fotki',
            name='ssilka',
        ),
        migrations.RemoveField(
            model_name='fotki',
            name='title',
        ),
        migrations.AddField(
            model_name='novinki',
            name='image',
            field=models.ImageField(default=1, upload_to='mebel/images/'),
            preserve_default=False,
        ),
    ]
