# Generated by Django 4.1.2 on 2022-10-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0034_remove_fotki_price_remove_fotki_ssilka_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cresla',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='cresla',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='cresla',
            name='image7',
        ),
        migrations.AlterField(
            model_name='crovati',
            name='height_izg',
            field=models.CharField(max_length=150, verbose_name='Высота изголовья'),
        ),
    ]
