# Generated by Django 4.1.2 on 2022-10-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0035_remove_cresla_image5_remove_cresla_image6_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cresla',
            name='price1',
        ),
        migrations.AlterField(
            model_name='cresla',
            name='ott_dlin',
            field=models.CharField(max_length=150, verbose_name='Длина оттоманки'),
        ),
        migrations.AlterField(
            model_name='cresla',
            name='ott_width',
            field=models.CharField(max_length=150, verbose_name='Ширина оттоманки'),
        ),
        migrations.AlterField(
            model_name='cresla',
            name='price',
            field=models.IntegerField(verbose_name='цена(вместе с оттоманкой)'),
        ),
    ]
