# Generated by Django 4.1.2 on 2022-10-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0036_remove_cresla_price1_alter_cresla_ott_dlin_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Novinki',
        ),
        migrations.AddField(
            model_name='barnie_stulya',
            name='Novinki',
            field=models.BooleanField(default=1, verbose_name='Новинки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cresla',
            name='Novinki',
            field=models.BooleanField(default=1, verbose_name='Новинки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crovati',
            name='Novinki',
            field=models.BooleanField(default=1, verbose_name='Новинки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='divani',
            name='Novinki',
            field=models.BooleanField(default=1, verbose_name='Новинки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stoli',
            name='Novinki',
            field=models.BooleanField(default=1, verbose_name='Новинки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stulia',
            name='Novinki',
            field=models.BooleanField(default=1, verbose_name='Новинки'),
            preserve_default=False,
        ),
    ]
