# Generated by Django 4.1.2 on 2022-11-12 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0040_alter_divani_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stoli',
            name='diametr',
            field=models.CharField(max_length=200, verbose_name='Диаметр'),
        ),
        migrations.AlterField(
            model_name='stoli',
            name='dlina',
            field=models.CharField(max_length=200, verbose_name='Длина'),
        ),
        migrations.AlterField(
            model_name='stoli',
            name='height',
            field=models.CharField(max_length=200, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='stoli',
            name='width',
            field=models.CharField(max_length=200, verbose_name='Ширина'),
        ),
    ]
