# Generated by Django 4.1.2 on 2022-11-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0041_alter_stoli_diametr_alter_stoli_dlina_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stulia',
            name='deep',
            field=models.CharField(max_length=150, verbose_name='Глубина'),
        ),
        migrations.AlterField(
            model_name='stulia',
            name='width',
            field=models.CharField(max_length=150, verbose_name='Ширина'),
        ),
    ]
